name: shellcheck

on:
  pull_request:
    branches:
      - v1
      - master
      - architecture

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: change working directory
        run: cd src/

      - name: shellcheck
        run: shellcheck *

