name: shellcheck

on:
  pull_request:
    branches:
      - v1
      - master
      - architecture

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: ./build.sh

      - name: shellcheck
        run: shellcheck build/foopak

